#!/bin/bash
# Clean slate setup - Removes all containers, volumes, and config

set -e

echo "🧹 Cleaning up old containers and volumes..."

# Stop and remove ALL containers (including volumes)
docker compose down -v 2>/dev/null || true

# Delete .env file (fresh passwords will be generated by setup.sh)
if [ -f .env ]; then
    rm .env
    echo "✅ Deleted old .env file"
fi

# Delete .setup-info if it exists
if [ -f .setup-info ]; then
    rm .setup-info
    echo "✅ Deleted old .setup-info file"
fi

echo "✅ Old containers, volumes, and config removed"
echo ""
echo "🚀 Running setup.sh to generate fresh environment..."
echo ""

# Run setup script
./setup.sh
