-- ============================================================================
-- MULTIMODAL CONTENT SUPPORT SCHEMA
-- Version: 005
-- Description: Add schema support for multimodal embeddings (vision).
-- This includes support for carousel posts and storing AI-generated
-- descriptions of visual content (images/videos).
-- ============================================================================

-- ============================================================================
-- 1. ADD TABLE FOR CAROUSEL/CHILD MEDIA
-- ============================================================================

-- This table stores individual media items for a carousel post.
CREATE TABLE IF NOT EXISTS instagram_post_children (
    id VARCHAR(255) PRIMARY KEY,
    post_id VARCHAR(255) NOT NULL REFERENCES instagram_posts(id) ON DELETE CASCADE,
    client_id VARCHAR(255) NOT NULL,
    media_type VARCHAR(50) NOT NULL, -- IMAGE, VIDEO
    media_url TEXT,
    permalink TEXT,
    thumbnail_url TEXT,
    timestamp TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_instagram_post_children_post_id ON instagram_post_children(post_id);
CREATE INDEX IF NOT EXISTS idx_instagram_post_children_client_id ON instagram_post_children(client_id);

COMMENT ON TABLE instagram_post_children IS 'Stores individual media items (images, videos) for a single Instagram carousel post.';

-- ============================================================================
-- 2. ADD VISION DESCRIPTION COLUMN TO MAIN POSTS TABLE
-- ============================================================================

-- This column will store the text generated by a vision model describing the post's visual content.
ALTER TABLE instagram_posts
    ADD COLUMN IF NOT EXISTS vision_description TEXT;

COMMENT ON COLUMN instagram_posts.vision_description IS 'AI-generated text description of the post''s visual content (image, video, or carousel).';

-- ============================================================================
-- MIGRATION COMPLETE
-- ============================================================================
